"""followers

Revision ID: 18248a947b93
Revises: bbd94876ee9a
Create Date: 2020-11-21 12:13:00.046564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18248a947b93'
down_revision = 'bbd94876ee9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
